### ISSUE TITLE
Admin Inventory Management

### ISSUE THREAD

**Issue by hoanhan101** [bennington-hardware-hacking-2019/pos_system#15]
We need a way to add, update, delete, and otherwise manage the inventory. We have the DB queries built. We need the UI for it.

**Comment by awbry** [comment]
okay, so because of 42b3e6e56b6fd333a0842c2e613869e30c4c52d1 we should be in a position to work on this!

**Comment by MattCollyer** [comment]
Hey @hoanhan101, I think we'll need to use the socket for logging in an admin (enhancement), and checking for a tag when the admin is adding an item to db. (bug) I commented ur name in the code where its needed (server branch, server api.py)

**Comment by hoanhan101** [comment]
@MattCollyer i added in websocket changes to the server. feel free to modify the code and make changes if needed. i won't touch on these admin related routes so don't worry about the conflict changes.

**Comment by awbry** [comment]
I reopened the server branch and restored/fine-tuned the admin inventory management setup. The only part of Admin Inventory Management left to do is genuinely adding tags to items (bug). We could also consider allowing login by card (enhancement)

**Comment by awbry** [comment]
- [x] implement add item tags
- [x] implement add buyer card

**Comment by hoanhan101** [comment]
fixed in #37
