### ISSUE TITLE
frontend websocket

### ISSUE THREAD

**Issue by hoanhan101** [bennington-hardware-hacking-2019/pos_system#17]
This is the front end of the UI component

**Comment by awbry** [comment]
work on this issue is being done [here](https://github.com/bennington-hardware-hacking-2019/NFC_Systems/tree/vue.js) for now. @zalkar-z and @hoanhan101 will migrate it to pos_system when its ready to integrate

**Comment by awbry** [comment]
Work here is toward #23 and #15. Check both issues for updates

**Comment by hoanhan101** [comment]
fixed in #37
