### ISSUE TITLE
Fool-Proof Enclosure

### ISSUE THREAD

**Issue by hoanhan101** [bennington-hardware-hacking-2019/pos_system#21]
Our hardware needs to stay safe from customers like Matthew Collyer and his cat army

**Comment by awbry** [comment]
@fivegrant is working hard on this! ❤️

**Comment by awbry** [comment]
We have a complete enclosure!!
![IMG_20190528_210305](https://user-images.githubusercontent.com/25990185/58560201-a150b300-81f2-11e9-8063-67a80d3c518f.jpg)
