### ISSUE TITLE
Connect UI to Controller

### ISSUE THREAD

**Issue by hoanhan101** [bennington-hardware-hacking-2019/pos_system#27]
We need to initialize the UI from the controller.

**Comment by awbry** [comment]
to accomplish this, as @hoanhan101 and I discussed in class, we will run the server from the controller — in fact the server will BE the controller — so we will rename controller to server

**Comment by awbry** [comment]
I think I have done as much of this as was necessary before websockets can get involved
see 42b3e6e56b6fd333a0842c2e613869e30c4c52d1
