### ISSUE TITLE
handle websocket event thread properly

### ISSUE THREAD

**Issue by hoanhan101** [bennington-hardware-hacking-2019/pos_system#34]
at the moment, we start a background thread to read the nfc tag continuously until receiving a cancel signal, aka a checkout_request. however, after a cancel signal, the thread still persists until a last and final reading.

if time allows, will fix this before the last class. else, have to defer it because this is not a priority.

**Comment by awbry** [comment]
@hoanhan101 your self.add_tags fix takes care of this 👍
